---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
  - verbs:
      - list
      - watch
    apiGroups:
      - extensions
      - apps
    resources:
      - daemonsets
  - verbs:
      - list
      - watch
    apiGroups:
      - extensions
      - apps
    resources:
      - deployments
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
  - verbs:
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - list
      - watch
    apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - limitranges
  - verbs:
      - list
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumes
  - verbs:
      - list
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - list
      - watch
    apiGroups:
      - extensions
      - apps
    resources:
      - replicasets
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - replicationcontrollers
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - resourcequotas
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - list
      - watch
    apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
  - verbs:
      - list
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
  - verbs:
      - list
      - watch
    apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
  - verbs:
      - list
      - watch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics
secrets:
  - name: kube-state-metrics-token
