sshd_allow_agent_forwarding: "no"
sshd_allow_tcp_forwarding: "no"
sshd_authorized_keys_file: ".ssh/authorized_keys"
sshd_ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
sshd_client_alive_count_max: "3"
sshd_client_interval: "0"
sshd_compression: "no"
sshd_gssapi_authentication: "no"
sshd_host_key_algorithms: "ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com"
sshd_kerberos_authentication: "no"
sshd_kex_algorithms: "curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521"
sshd_listen_address: "0.0.0.0"
sshd_log_level: "INFO"
sshd_macs: "hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
sshd_max_auth_tries: "3"
sshd_max_sessions: "3"
sshd_password_authentication: "no"
sshd_permit_empty_passwords: "no"
sshd_permit_root_login: "no"
sshd_permit_tunnel: "no"
sshd_permit_user_environment: "no"
sshd_port: "22"
sshd_pubkey_authentication: "yes"
sshd_tcp_keep_alive: "yes"
sshd_use_dns: "no"
sshd_x11_forwarding: "no"