name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "37 13 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          close-issue-message: "This issue was closed because it has been stalled for 7 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          days-before-issue-stale: 180
          days-before-pr-stale: 180
          days-before-issue-close: 7
          days-before-pr-close: 7
          exempt-issue-labels: "in progress"
          exempt-pr-labels: "in progress"
